# Generated by Django 5.2.1 on 2025-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='words',
            field=models.ManyToManyField(related_name='dictionaries', through='api.DictionaryEntry', to='api.word'),
        ),
    ]
