# Generated by Django 5.2.1 on 2025-05-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.CharField(choices=[('opened', 'Открыт для других пользователей'), ('closed', 'Закрыт для других пользователей')], default='closed', max_length=10),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.text')),
            ],
            options={
                'ordering': ['section_index'],
                'unique_together': {('text', 'section_index')},
            },
        ),
    ]
