# Generated by Django 5.2.1 on 2025-05-14 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_text_content_alter_text_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='morph_analysis',
        ),
        migrations.AddField(
            model_name='word',
            name='section',
            field=models.ManyToManyField(related_name='words', to='api.textsection'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=50)),
                ('morph', models.JSONField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.word')),
            ],
        ),
    ]
